# Accès à l'application front : http://localhost:4200

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - frontend-network
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: pg_isready -U admin -d appdb
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
